// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities.
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;

    obx_model_entity(model, "Chunk", 1, 9179932940592290193);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2455507974577173176);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "document_id", OBXPropertyType_Long, 2, 8084283936309515694);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "content", OBXPropertyType_String, 3, 6702692769779061836);
    obx_model_property(model, "vector", OBXPropertyType_FloatVector, 4, 1462046374052066066);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED);
    obx_model_property_index_id(model, 1, 6849331268428372200);
    obx_model_property_index_hnsw_dimensions(model, 1024);
    obx_model_property_index_hnsw_distance_type(model, OBXVectorDistanceType_Euclidean);
    obx_model_property_index_hnsw_neighbors_per_node(model, 30);
    obx_model_property_index_hnsw_indexing_search_count(model, 200);
    obx_model_property(model, "token_ids", OBXPropertyType_ByteVector, 5, 334330371521458599);
    obx_model_property(model, "chunk_index", OBXPropertyType_Int, 6, 2975675897590904734);
    obx_model_property(model, "kiwi_tokens", OBXPropertyType_ByteVector, 7, 3342692050699206522);
    obx_model_property(model, "created_at", OBXPropertyType_Long, 8, 3806205333954610445);
    obx_model_property(model, "source_type", OBXPropertyType_Short, 9, 4330687298636121811);
    obx_model_property(model, "sender", OBXPropertyType_String, 10, 4405251715006746188);
    obx_model_property(model, "document_external_id", OBXPropertyType_String, 11, 5566223344112233001);
    obx_model_entity_last_property_id(model, 11, 5566223344112233001);

    obx_model_entity(model, "Document", 2, 6143900362527639746);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4741398273188845619);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "content", OBXPropertyType_String, 2, 5264333650679258855);
    obx_model_property(model, "_id", OBXPropertyType_String, 3, 1155826969108657222);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 1389202326276852715);
    obx_model_property(model, "created_at", OBXPropertyType_Long, 5, 1932946672565023347);
    obx_model_property(model, "source_type", OBXPropertyType_Short, 6, 2000003994095602920);
    obx_model_property(model, "sender", OBXPropertyType_String, 7, 2260174545979689167);
    obx_model_entity_last_property_id(model, 7, 2260174545979689167);

    // Query (entity 3) and GroundTruth (entity 4) retired — moved to BenchmarkObxManager (separate DB)
    // lastEntityId and lastIndexId must never decrease
    obx_model_last_entity_id(model, 4, 7401141559179126524);
    obx_model_last_index_id(model, 2, 1164857942749024190);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
