// Code generated by ObjectBox; DO NOT EDIT.

#include "schema.obx.hpp"

// ==================== Chunk ====================

const obx::Property<ecovector::Chunk, OBXPropertyType_Long> ecovector::Chunk_::id(1);
const obx::Property<ecovector::Chunk, OBXPropertyType_Long> ecovector::Chunk_::document_id(2);
const obx::Property<ecovector::Chunk, OBXPropertyType_String> ecovector::Chunk_::content(3);
const obx::Property<ecovector::Chunk, OBXPropertyType_FloatVector> ecovector::Chunk_::vector(4);
const obx::Property<ecovector::Chunk, OBXPropertyType_ByteVector> ecovector::Chunk_::token_ids(5);
const obx::Property<ecovector::Chunk, OBXPropertyType_Int> ecovector::Chunk_::chunk_index(6);
const obx::Property<ecovector::Chunk, OBXPropertyType_ByteVector> ecovector::Chunk_::kiwi_tokens(7);
const obx::Property<ecovector::Chunk, OBXPropertyType_Long> ecovector::Chunk_::created_at(8);
const obx::Property<ecovector::Chunk, OBXPropertyType_Short> ecovector::Chunk_::source_type(9);
const obx::Property<ecovector::Chunk, OBXPropertyType_String> ecovector::Chunk_::sender(10);
const obx::Property<ecovector::Chunk, OBXPropertyType_String> ecovector::Chunk_::document_external_id(11);

void ecovector::Chunk::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ecovector::Chunk& object) {
    fbb.Clear();
    auto offsetcontent = fbb.CreateString(object.content);
    auto offsetvector = fbb.CreateVector(object.vector);
    auto offsettoken_ids = fbb.CreateVector(object.token_ids);
    auto offsetkiwi_tokens = fbb.CreateVector(object.kiwi_tokens);
    auto offsetsender = fbb.CreateString(object.sender);
    auto offsetdocument_external_id = fbb.CreateString(object.document_external_id);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddElement(6, object.document_id);
    fbb.AddOffset(8, offsetcontent);
    fbb.AddOffset(10, offsetvector);
    fbb.AddOffset(12, offsettoken_ids);
    fbb.AddElement(14, object.chunk_index);
    fbb.AddOffset(16, offsetkiwi_tokens);
    fbb.AddElement(18, object.created_at);
    fbb.AddElement(20, object.source_type);
    fbb.AddOffset(22, offsetsender);
    fbb.AddOffset(24, offsetdocument_external_id);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ecovector::Chunk ecovector::Chunk::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ecovector::Chunk object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ecovector::Chunk> ecovector::Chunk::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ecovector::Chunk>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ecovector::Chunk::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ecovector::Chunk& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    outObject.document_id = table->GetField<uint64_t>(6, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject.content.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.content.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<float>*>(10);
        if (ptr) {
            outObject.vector.assign(ptr->begin(), ptr->end());
        } else {
            outObject.vector.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<uint8_t>*>(12);
        if (ptr) {
            outObject.token_ids.assign(ptr->begin(), ptr->end());
        } else {
            outObject.token_ids.clear();
        }
    }
    outObject.chunk_index = table->GetField<int32_t>(14, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<uint8_t>*>(16);
        if (ptr) {
            outObject.kiwi_tokens.assign(ptr->begin(), ptr->end());
        } else {
            outObject.kiwi_tokens.clear();
        }
    }
    outObject.created_at = table->GetField<int64_t>(18, 0);
    outObject.source_type = table->GetField<int16_t>(20, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(22);
        if (ptr) {
            outObject.sender.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.sender.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(24);
        if (ptr) {
            outObject.document_external_id.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.document_external_id.clear();
        }
    }
}

// ==================== Document ====================

const obx::Property<ecovector::Document, OBXPropertyType_Long> ecovector::Document_::id(1);
const obx::Property<ecovector::Document, OBXPropertyType_String> ecovector::Document_::content(2);
const obx::Property<ecovector::Document, OBXPropertyType_String> ecovector::Document_::_id(3);
const obx::Property<ecovector::Document, OBXPropertyType_String> ecovector::Document_::description(4);
const obx::Property<ecovector::Document, OBXPropertyType_Long> ecovector::Document_::created_at(5);
const obx::Property<ecovector::Document, OBXPropertyType_Short> ecovector::Document_::source_type(6);
const obx::Property<ecovector::Document, OBXPropertyType_String> ecovector::Document_::sender(7);

void ecovector::Document::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const ecovector::Document& object) {
    fbb.Clear();
    auto offsetcontent = fbb.CreateString(object.content);
    auto offset_id = fbb.CreateString(object._id);
    auto offsetdescription = fbb.CreateString(object.description);
    auto offsetsender = fbb.CreateString(object.sender);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetcontent);
    fbb.AddOffset(8, offset_id);
    fbb.AddOffset(10, offsetdescription);
    fbb.AddElement(12, object.created_at);
    fbb.AddElement(14, object.source_type);
    fbb.AddOffset(16, offsetsender);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

ecovector::Document ecovector::Document::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    ecovector::Document object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<ecovector::Document> ecovector::Document::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<ecovector::Document>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void ecovector::Document::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, ecovector::Document& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(6);
        if (ptr) {
            outObject.content.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.content.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(8);
        if (ptr) {
            outObject._id.assign(ptr->c_str(), ptr->size());
        } else {
            outObject._id.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(10);
        if (ptr) {
            outObject.description.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.description.clear();
        }
    }
    outObject.created_at = table->GetField<int64_t>(12, 0);
    outObject.source_type = table->GetField<int16_t>(14, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::String*>(16);
        if (ptr) {
            outObject.sender.assign(ptr->c_str(), ptr->size());
        } else {
            outObject.sender.clear();
        }
    }
}

// Query (entity 3) and GroundTruth (entity 4) retired — moved to BenchmarkObxManager (separate DB)
