// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


namespace ecovector {
struct Chunk_;

struct Chunk {
    obx_id id;
    uint64_t document_id;
    std::string content;
    std::vector<float> vector;
    std::vector<uint8_t> token_ids;
    int32_t chunk_index = 0;
    std::vector<uint8_t> kiwi_tokens;
    int64_t created_at = 0;
    int16_t source_type = 0;
    std::string sender;
    std::string document_external_id;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }

        static void setObjectId(Chunk& object, obx_id newId) { object.id = newId; }

        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Chunk& object);

        /// Read an object from a valid FlatBuffer
        static Chunk fromFlatBuffer(const void* data, size_t size);

        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Chunk> newFromFlatBuffer(const void* data, size_t size);

        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Chunk& outObject);
    };
};

struct Chunk_ {
    static const obx::Property<Chunk, OBXPropertyType_Long> id;
    static const obx::Property<Chunk, OBXPropertyType_Long> document_id;
    static const obx::Property<Chunk, OBXPropertyType_String> content;
    static const obx::Property<Chunk, OBXPropertyType_FloatVector> vector;
    static const obx::Property<Chunk, OBXPropertyType_ByteVector> token_ids;
    static const obx::Property<Chunk, OBXPropertyType_Int> chunk_index;
    static const obx::Property<Chunk, OBXPropertyType_ByteVector> kiwi_tokens;
    static const obx::Property<Chunk, OBXPropertyType_Long> created_at;
    static const obx::Property<Chunk, OBXPropertyType_Short> source_type;
    static const obx::Property<Chunk, OBXPropertyType_String> sender;
    static const obx::Property<Chunk, OBXPropertyType_String> document_external_id;
};
}  // namespace ecovector


namespace ecovector {
struct Document_;

struct Document {
    obx_id id;
    std::string content;
    std::string _id;
    std::string description;
    int64_t created_at = 0;
    int16_t source_type = 0;
    std::string sender;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 2; }

        static void setObjectId(Document& object, obx_id newId) { object.id = newId; }

        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Document& object);

        /// Read an object from a valid FlatBuffer
        static Document fromFlatBuffer(const void* data, size_t size);

        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Document> newFromFlatBuffer(const void* data, size_t size);

        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Document& outObject);
    };
};

struct Document_ {
    static const obx::Property<Document, OBXPropertyType_Long> id;
    static const obx::Property<Document, OBXPropertyType_String> content;
    static const obx::Property<Document, OBXPropertyType_String> _id;
    static const obx::Property<Document, OBXPropertyType_String> description;
    static const obx::Property<Document, OBXPropertyType_Long> created_at;
    static const obx::Property<Document, OBXPropertyType_Short> source_type;
    static const obx::Property<Document, OBXPropertyType_String> sender;
};
}  // namespace ecovector

// Query (entity 3) and GroundTruth (entity 4) retired — moved to BenchmarkObxManager (separate DB)
